apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-pod
  template:
    metadata:
      labels:
        app: api-gateway-pod
    spec:
      containers:
        - name: api-gateway-server
          image: gcr.io/${PROJECT_ID}/api-gateway
          imagePullPolicy: Always
          ports:
            - name: api-gateway
              containerPort: 4241
          env:
            - name: PROJECT_ID
              value: '${PROJECT_ID}'
