apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-server
          image: gcr.io/gks-cluster-353716/auth
          imagePullPolicy: Always
          ports:
            - name: auth
              containerPort: 4240
