apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
        - name: db-server
          image: gcr.io/gks-cluster-353716/db
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              value: '6545352'
          ports:
            - name: db
              containerPort: 5432
