apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-server
          image: gcr.io/k8s-rent/users
          imagePullPolicy: Always
          ports:
            - name: users
              containerPort: 4243
